name: Test rq

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Python${{ matrix.python-version }}/Redis${{ matrix.redis-version }}/redis-py${{ matrix.redis-py-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
        redis-version: [3, 4, 5, 6]
        redis-py-version: [3.5.0]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install redis==${{ matrix.redis-py-version }}
        pip install -r requirements.txt -r dev-requirements.txt
        pip install -e .

    - name: Test with pytest
      run: |
        RUN_SLOW_TESTS_TOO=1 pytest --cov=./ --cov-report=xml --durations=5

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
